# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
