# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.cache/wt [current_project]
set_property parent.project_path f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0.xci
set_property is_locked true [get_files f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top fir_compiler_0 -part xc7z020clg484-2 -mode out_of_context
rename_ref -prefix_all fir_compiler_0_
write_checkpoint -noxdef fir_compiler_0.dcp
catch { report_utilization -file fir_compiler_0_utilization_synth.rpt -pb fir_compiler_0_utilization_synth.pb }
if { [catch {
  file copy -force f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.runs/fir_compiler_0_synth_1/fir_compiler_0.dcp f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.ip_user_files/ip/fir_compiler_0]} {
  catch { 
    file copy -force f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_stub.v f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.ip_user_files/ip/fir_compiler_0
  }
}

if {[file isdir f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.ip_user_files/ip/fir_compiler_0]} {
  catch { 
    file copy -force f:/Project/RG-2018-YF-001/FPGA/YF-012-V2.1-FPGA/YF-012-V1.0-FPGA/Miz_ip_lib/DataGenV5_3ch_mod/sources_1/src/fir_compiler_0/fir_compiler_0_stub.vhdl f:/project/rg-2018-yf-001/fpga/yf-012-v2.1-fpga/yf-012-v1.0-fpga/yf-012-v1.0-fpga.tmp/datagen_3ch_v1_0_project/DataGen_3ch_v1_0_project.ip_user_files/ip/fir_compiler_0
  }
}
