# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_top.xdc

# Block Designs: bd/design_ps/design_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps || ORIG_REF_NAME==design_ps}]

# IP: bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_processing_system7_0_0 || ORIG_REF_NAME==design_ps_processing_system7_0_0}]

# IP: bd/design_ps/ip/design_ps_axi_dma_0_0/design_ps_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_dma_0_0 || ORIG_REF_NAME==design_ps_axi_dma_0_0}]

# IP: bd/design_ps/ip/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axis_data_fifo_0_0 || ORIG_REF_NAME==design_ps_axis_data_fifo_0_0}]

# IP: bd/design_ps/ip/design_ps_axi_mem_intercon_0/design_ps_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_mem_intercon_0 || ORIG_REF_NAME==design_ps_axi_mem_intercon_0}]

# IP: bd/design_ps/ip/design_ps_rst_processing_system7_0_100M_0/design_ps_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_ps_rst_processing_system7_0_100M_0}]

# IP: bd/design_ps/ip/design_ps_processing_system7_0_axi_periph_0/design_ps_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_ps_processing_system7_0_axi_periph_0}]

# IP: bd/design_ps/ip/design_ps_xbar_0/design_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xbar_0 || ORIG_REF_NAME==design_ps_xbar_0}]

# IP: bd/design_ps/ip/design_ps_xbar_1/design_ps_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xbar_1 || ORIG_REF_NAME==design_ps_xbar_1}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_0_0/design_ps_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_0 || ORIG_REF_NAME==design_ps_axi_gpio_0_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_0_1/design_ps_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_1 || ORIG_REF_NAME==design_ps_axi_gpio_0_1}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_1_0/design_ps_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_0 || ORIG_REF_NAME==design_ps_axi_gpio_1_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_0/design_ps_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_0 || ORIG_REF_NAME==design_ps_axi_gpio_2_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_1/design_ps_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_1 || ORIG_REF_NAME==design_ps_axi_gpio_2_1}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_2/design_ps_axi_gpio_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_2 || ORIG_REF_NAME==design_ps_axi_gpio_2_2}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_4_0/design_ps_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_0 || ORIG_REF_NAME==design_ps_axi_gpio_4_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_4_1/design_ps_axi_gpio_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_1 || ORIG_REF_NAME==design_ps_axi_gpio_4_1}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_4_2/design_ps_axi_gpio_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_2 || ORIG_REF_NAME==design_ps_axi_gpio_4_2}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_0_2/design_ps_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_2 || ORIG_REF_NAME==design_ps_axi_gpio_0_2}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_1_1/design_ps_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_1 || ORIG_REF_NAME==design_ps_axi_gpio_1_1}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_1_2/design_ps_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_2 || ORIG_REF_NAME==design_ps_axi_gpio_1_2}]

# IP: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/design_ps_DataGen_3ch_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_DataGen_3ch_0_1 || ORIG_REF_NAME==design_ps_DataGen_3ch_0_1}]

# IP: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/src/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}]

# IP: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/pretrig_fifo/pretrig_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pretrig_fifo || ORIG_REF_NAME==pretrig_fifo}]

# IP: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}]

# IP: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_1_3/design_ps_axi_gpio_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_3 || ORIG_REF_NAME==design_ps_axi_gpio_1_3}]

# IP: bd/design_ps/ip/design_ps_xlconstant_0_3/design_ps_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xlconstant_0_3 || ORIG_REF_NAME==design_ps_xlconstant_0_3}]

# IP: bd/design_ps/ip/design_ps_clk_wiz_0_0/design_ps_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_clk_wiz_0_0 || ORIG_REF_NAME==design_ps_clk_wiz_0_0}]

# IP: bd/design_ps/ip/design_ps_xadc_wiz_0_0/design_ps_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xadc_wiz_0_0 || ORIG_REF_NAME==design_ps_xadc_wiz_0_0}]

# IP: bd/design_ps/ip/design_ps_Timer_10us_m_0_0/design_ps_Timer_10us_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_Timer_10us_m_0_0 || ORIG_REF_NAME==design_ps_Timer_10us_m_0_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_13_0/design_ps_axi_gpio_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_13_0 || ORIG_REF_NAME==design_ps_axi_gpio_13_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_14_0/design_ps_axi_gpio_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_14_0 || ORIG_REF_NAME==design_ps_axi_gpio_14_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_15_0/design_ps_axi_gpio_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_15_0 || ORIG_REF_NAME==design_ps_axi_gpio_15_0}]

# IP: bd/design_ps/ip/design_ps_axi_uartlite_0_0/design_ps_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_uartlite_0_0 || ORIG_REF_NAME==design_ps_axi_uartlite_0_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_16_0/design_ps_axi_gpio_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_16_0 || ORIG_REF_NAME==design_ps_axi_gpio_16_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_17_0/design_ps_axi_gpio_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_17_0 || ORIG_REF_NAME==design_ps_axi_gpio_17_0}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_3/design_ps_axi_gpio_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_3 || ORIG_REF_NAME==design_ps_axi_gpio_2_3}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_4/design_ps_axi_gpio_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_4 || ORIG_REF_NAME==design_ps_axi_gpio_2_4}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_5/design_ps_axi_gpio_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_5 || ORIG_REF_NAME==design_ps_axi_gpio_2_5}]

# IP: bd/design_ps/ip/design_ps_axi_gpio_2_6/design_ps_axi_gpio_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_6 || ORIG_REF_NAME==design_ps_axi_gpio_2_6}]

# IP: bd/design_ps/ip/design_ps_tier2_xbar_0_0/design_ps_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_tier2_xbar_0_0 || ORIG_REF_NAME==design_ps_tier2_xbar_0_0}]

# IP: bd/design_ps/ip/design_ps_tier2_xbar_1_0/design_ps_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_tier2_xbar_1_0 || ORIG_REF_NAME==design_ps_tier2_xbar_1_0}]

# IP: bd/design_ps/ip/design_ps_tier2_xbar_2_0/design_ps_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_tier2_xbar_2_0 || ORIG_REF_NAME==design_ps_tier2_xbar_2_0}]

# IP: bd/design_ps/ip/design_ps_tier2_xbar_3_0/design_ps_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_tier2_xbar_3_0 || ORIG_REF_NAME==design_ps_tier2_xbar_3_0}]

# IP: bd/design_ps/ip/design_ps_auto_pc_0/design_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_auto_pc_0 || ORIG_REF_NAME==design_ps_auto_pc_0}]

# IP: bd/design_ps/ip/design_ps_auto_us_0/design_ps_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_auto_us_0 || ORIG_REF_NAME==design_ps_auto_us_0}]

# IP: bd/design_ps/ip/design_ps_auto_pc_1/design_ps_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_auto_pc_1 || ORIG_REF_NAME==design_ps_auto_pc_1}]

# XDC: bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_processing_system7_0_0 || ORIG_REF_NAME==design_ps_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_axi_dma_0_0/design_ps_axi_dma_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_dma_0_0/design_ps_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_dma_0_0 || ORIG_REF_NAME==design_ps_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_dma_0_0/design_ps_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_dma_0_0 || ORIG_REF_NAME==design_ps_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axis_data_fifo_0_0 || ORIG_REF_NAME==design_ps_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0/design_ps_axis_data_fifo_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axis_data_fifo_0_0 || ORIG_REF_NAME==design_ps_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_rst_processing_system7_0_100M_0/design_ps_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_ps_rst_processing_system7_0_100M_0}]

# XDC: bd/design_ps/ip/design_ps_rst_processing_system7_0_100M_0/design_ps_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_ps_rst_processing_system7_0_100M_0}]

# XDC: bd/design_ps/ip/design_ps_rst_processing_system7_0_100M_0/design_ps_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_xbar_0/design_ps_xbar_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_xbar_1/design_ps_xbar_1_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_0/design_ps_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_0 || ORIG_REF_NAME==design_ps_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_0/design_ps_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_0/design_ps_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_0 || ORIG_REF_NAME==design_ps_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_1/design_ps_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_1 || ORIG_REF_NAME==design_ps_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_1/design_ps_axi_gpio_0_1_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_1/design_ps_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_1 || ORIG_REF_NAME==design_ps_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_0/design_ps_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_0 || ORIG_REF_NAME==design_ps_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_0/design_ps_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_0/design_ps_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_0 || ORIG_REF_NAME==design_ps_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_0/design_ps_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_0 || ORIG_REF_NAME==design_ps_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_0/design_ps_axi_gpio_2_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_0/design_ps_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_0 || ORIG_REF_NAME==design_ps_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_1/design_ps_axi_gpio_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_1 || ORIG_REF_NAME==design_ps_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_1/design_ps_axi_gpio_2_1_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_1/design_ps_axi_gpio_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_1 || ORIG_REF_NAME==design_ps_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_2/design_ps_axi_gpio_2_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_2 || ORIG_REF_NAME==design_ps_axi_gpio_2_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_2/design_ps_axi_gpio_2_2_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_2/design_ps_axi_gpio_2_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_2 || ORIG_REF_NAME==design_ps_axi_gpio_2_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_0/design_ps_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_0 || ORIG_REF_NAME==design_ps_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_0/design_ps_axi_gpio_4_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_0/design_ps_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_0 || ORIG_REF_NAME==design_ps_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_1/design_ps_axi_gpio_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_1 || ORIG_REF_NAME==design_ps_axi_gpio_4_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_1/design_ps_axi_gpio_4_1_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_1/design_ps_axi_gpio_4_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_1 || ORIG_REF_NAME==design_ps_axi_gpio_4_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_2/design_ps_axi_gpio_4_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_2 || ORIG_REF_NAME==design_ps_axi_gpio_4_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_2/design_ps_axi_gpio_4_2_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_4_2/design_ps_axi_gpio_4_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_4_2 || ORIG_REF_NAME==design_ps_axi_gpio_4_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_2/design_ps_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_2 || ORIG_REF_NAME==design_ps_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_2/design_ps_axi_gpio_0_2_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_0_2/design_ps_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_0_2 || ORIG_REF_NAME==design_ps_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_1/design_ps_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_1 || ORIG_REF_NAME==design_ps_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_1/design_ps_axi_gpio_1_1_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_1/design_ps_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_1 || ORIG_REF_NAME==design_ps_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_2/design_ps_axi_gpio_1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_2 || ORIG_REF_NAME==design_ps_axi_gpio_1_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_2/design_ps_axi_gpio_1_2_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_2/design_ps_axi_gpio_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_2 || ORIG_REF_NAME==design_ps_axi_gpio_1_2}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/src/fir_compiler_0/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/src/fir_compiler_0/fir_compiler_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/pretrig_fifo/pretrig_fifo/pretrig_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pretrig_fifo || ORIG_REF_NAME==pretrig_fifo}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_DataGen_3ch_0_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_3/design_ps_axi_gpio_1_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_3 || ORIG_REF_NAME==design_ps_axi_gpio_1_3}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_3/design_ps_axi_gpio_1_3_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_1_3/design_ps_axi_gpio_1_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_1_3 || ORIG_REF_NAME==design_ps_axi_gpio_1_3}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_clk_wiz_0_0/design_ps_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_clk_wiz_0_0 || ORIG_REF_NAME==design_ps_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_clk_wiz_0_0/design_ps_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_clk_wiz_0_0 || ORIG_REF_NAME==design_ps_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_clk_wiz_0_0/design_ps_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_xadc_wiz_0_0/design_ps_xadc_wiz_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_xadc_wiz_0_0/design_ps_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_xadc_wiz_0_0 || ORIG_REF_NAME==design_ps_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_13_0/design_ps_axi_gpio_13_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_13_0 || ORIG_REF_NAME==design_ps_axi_gpio_13_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_13_0/design_ps_axi_gpio_13_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_13_0/design_ps_axi_gpio_13_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_13_0 || ORIG_REF_NAME==design_ps_axi_gpio_13_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_14_0/design_ps_axi_gpio_14_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_14_0 || ORIG_REF_NAME==design_ps_axi_gpio_14_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_14_0/design_ps_axi_gpio_14_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_14_0/design_ps_axi_gpio_14_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_14_0 || ORIG_REF_NAME==design_ps_axi_gpio_14_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_15_0/design_ps_axi_gpio_15_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_15_0 || ORIG_REF_NAME==design_ps_axi_gpio_15_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_15_0/design_ps_axi_gpio_15_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_15_0/design_ps_axi_gpio_15_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_15_0 || ORIG_REF_NAME==design_ps_axi_gpio_15_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_uartlite_0_0/design_ps_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_uartlite_0_0 || ORIG_REF_NAME==design_ps_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_uartlite_0_0/design_ps_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_uartlite_0_0/design_ps_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_uartlite_0_0 || ORIG_REF_NAME==design_ps_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_16_0/design_ps_axi_gpio_16_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_16_0 || ORIG_REF_NAME==design_ps_axi_gpio_16_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_16_0/design_ps_axi_gpio_16_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_16_0/design_ps_axi_gpio_16_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_16_0 || ORIG_REF_NAME==design_ps_axi_gpio_16_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_17_0/design_ps_axi_gpio_17_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_17_0 || ORIG_REF_NAME==design_ps_axi_gpio_17_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_17_0/design_ps_axi_gpio_17_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_17_0/design_ps_axi_gpio_17_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_17_0 || ORIG_REF_NAME==design_ps_axi_gpio_17_0}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_3/design_ps_axi_gpio_2_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_3 || ORIG_REF_NAME==design_ps_axi_gpio_2_3}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_3/design_ps_axi_gpio_2_3_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_3/design_ps_axi_gpio_2_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_3 || ORIG_REF_NAME==design_ps_axi_gpio_2_3}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_4/design_ps_axi_gpio_2_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_4 || ORIG_REF_NAME==design_ps_axi_gpio_2_4}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_4/design_ps_axi_gpio_2_4_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_4/design_ps_axi_gpio_2_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_4 || ORIG_REF_NAME==design_ps_axi_gpio_2_4}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_5/design_ps_axi_gpio_2_5_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_5 || ORIG_REF_NAME==design_ps_axi_gpio_2_5}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_5/design_ps_axi_gpio_2_5_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_5/design_ps_axi_gpio_2_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_5 || ORIG_REF_NAME==design_ps_axi_gpio_2_5}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_6/design_ps_axi_gpio_2_6_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_6 || ORIG_REF_NAME==design_ps_axi_gpio_2_6}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_6/design_ps_axi_gpio_2_6_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_axi_gpio_2_6/design_ps_axi_gpio_2_6.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_axi_gpio_2_6 || ORIG_REF_NAME==design_ps_axi_gpio_2_6}] {/U0 }]/U0 ]]

# XDC: bd/design_ps/ip/design_ps_tier2_xbar_0_0/design_ps_tier2_xbar_0_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_tier2_xbar_1_0/design_ps_tier2_xbar_1_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_tier2_xbar_2_0/design_ps_tier2_xbar_2_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_tier2_xbar_3_0/design_ps_tier2_xbar_3_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_auto_pc_0/design_ps_auto_pc_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_auto_us_0/design_ps_auto_us_0_ooc.xdc

# XDC: bd/design_ps/ip/design_ps_auto_us_0/design_ps_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ps_auto_us_0 || ORIG_REF_NAME==design_ps_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/design_ps/ip/design_ps_auto_pc_1/design_ps_auto_pc_1_ooc.xdc

# XDC: bd/design_ps/design_ps_ooc.xdc
